<a href="https://colab.research.google.com/github/sonjoy1s/Kaggle_Deep_Lr/blob/main/ICU_Patient_Monitoring_%26_Mortality_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('/content/ICU_Patient_Monitoring_Mortality_Prediction_15000.csv')
df.head()

,patient_id,age,gender,admission_type,comorbidity_score,heart_rate_mean,heart_rate_std,heart_rate_max,heart_rate_min,systolic_bp_mean,...,glucose_mean,lactate_mean,urine_output_total,ventilation_required,vasopressor_used,length_of_stay_days,apache_score,sofa_score,sepsis_flag,mortality_label
0,PAT000001,32,Male,Urgent,3.75,136.06,19.64,162.01,127.16,104.04,...,73.71,7.77,4245.99,0,0,6.32,15.65,10.50,0,0
1,PAT000002,46,Male,Urgent,2.91,108.95,7.79,124.18,94.79,131.05,...,78.36,5.06,1267.36,0,1,29.00,33.29,6.09,0,1
2,PAT000003,87,Male,Urgent,6.84,95.21,7.44,117.54,89.35,171.84,...,168.41,1.89,4863.13,1,1,26.95,25.93,18.44,0,1
3,PAT000004,21,Male,Emergency,1.96,63.62,11.51,82.22,51.84,164.59,...,214.40,1.06,4940.99,1,0,1.16,33.54,14.14,0,1
4,PAT000005,21,Male,Urgent,7.71,65.92,12.17,74.98,39.34,146.10,...,201.33,5.28,4492.46,0,0,21.68,31.63,11.23,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   patient_id             15000 non-null  object
 1   age                    15000 non-null  int64
 2   gender                 15000 non-null  object
 3   admission_type         15000 non-null  object
 4   comorbidity_score      15000 non-null  float64
 5   heart_rate_mean        15000 non-null  float64
 6   heart_rate_std         15000 non-null  float64
 7   heart_rate_max         15000 non-null  float64
 8   heart_rate_min         15000 non-null  float64
 9   systolic_bp_mean       15000 non-null  float64
 10  systolic_bp_std        15000 non-null  float64
 11  respiratory_rate_mean  15000 non-null  float64
 12  spo2_mean              15000 non-null  float64
 13  temperature_mean       15000 non-null  float64
 14  glucose_mean           15000 non-null  float64
 15  lactate_mean           15000 non-null  float64
 16  urine_output_total     15000 non-null  float64
 17  ventilation_required   15000 non-null  int64
 18  vasopressor_used       15000 non-null  int64
 19  length_of_stay_days    15000 non-null  float64
 20  apache_score           15000 non-null  float64
 21  sofa_score             15000 non-null  float64
 22  sepsis_flag            15000 non-null  int64
 23  mortality_label        15000 non-null  int64
dtypes: float64(16), int64(5), object(3)
memory usage: 2.7+ MB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,15000.0,53.987533,21.027881,18.00,36.0000,54.000,72.0000,90.00
comorbidity_score,15000.0,4.988851,2.896171,0.00,2.4200,4.980,7.5400,10.00
heart_rate_mean,15000.0,100.026900,23.187937,60.00,80.0275,99.925,120.1600,140.00
heart_rate_std,15000.0,15.087800,5.780114,5.00,10.0775,15.180,20.0800,25.00
heart_rate_max,15000.0,122.477551,25.304740,65.26,102.4300,122.450,142.4650,179.32
heart_rate_min,15000.0,82.523059,24.393954,30.60,62.2075,82.575,102.8425,134.33
systolic_bp_mean,15000.0,134.780335,25.982344,90.01,112.1875,134.555,157.3700,180.00
systolic_bp_std,15000.0,12.539299,4.327404,5.00,8.7800,12.570,16.2600,20.00
respiratory_rate_mean,15000.0,23.612935,6.654296,12.00,17.8800,23.650,29.4000,35.00
spo2_mean,15000.0,90.051769,5.750619,80.00,85.0800,90.020,95.0000,100.00
temperature_mean,15000.0,37.503707,1.446096,35.00,36.2500,37.520,38.7600,40.00
glucose_mean,15000.0,159.115675,51.867736,70.01,114.4300,158.615,203.8700,249.98
lactate_mean,15000.0,4.270719,2.154312,0.50,2.4200,4.290,6.1200,8.00
urine_output_total,15000.0,2760.416425,1297.457979,500.03,1636.3550,2767.555,3887.7800,4999.54
ventilation_required,15000.0,0.302200,0.459227,0.00,0.0000,0.000,1.0000,1.00
vasopressor_used,15000.0,0.245133,0.430181,0.00,0.0000,0.000,0.0000,1.00
length_of_stay_days,15000.0,15.432166,8.368326,1.00,8.1400,15.470,22.6700,30.00
apache_score,15000.0,22.496783,10.087201,5.00,13.6400,22.635,31.1400,40.00
sofa_score,15000.0,9.982515,5.747374,0.00,4.9675,10.040,14.9300,20.00
sepsis_flag,15000.0,0.201933,0.401456,0.00,0.0000,0.000,0.0000,1.00
mortality_label,15000.0,0.227867,0.419470,0.00,0.0000,0.000,0.0000,1.00